In [40]:
#exploratory analysis in python 
#load the libraries and the dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# load data
df = pd.read_csv("C:/Users/ahafeez7/Downloads/780/lm6_q03/highUtilizerY2.csv")

# quick look
df.head()

,patient_id,ELIX1,ELIX10,ELIX11,ELIX12,ELIX13,ELIX14,ELIX15,ELIX16,ELIX17,...,ELIX29,ELIX3,ELIX4,ELIX5,ELIX6,ELIX7,ELIX8,ELIX9,countClaims,highUtilizer
0,PAT164485,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,24,0
1,PAT179988,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,1,23,0
2,PAT67520,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,17,0
3,PAT22707,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,0
4,PAT40696,0,0,1,1,1,0,0,0,0,...,1,0,0,0,1,0,0,1,127,1

In [42]:
#basic structure
# shape
print("shape:", df.shape)

# column names
print(df.columns)

# data types
df.info()

shape: (8000, 32)
Index(['patient_id', 'ELIX1', 'ELIX10', 'ELIX11', 'ELIX12', 'ELIX13', 'ELIX14',
       'ELIX15', 'ELIX16', 'ELIX17', 'ELIX18', 'ELIX19', 'ELIX2', 'ELIX20',
       'ELIX21', 'ELIX22', 'ELIX23', 'ELIX24', 'ELIX25', 'ELIX26', 'ELIX27',
       'ELIX28', 'ELIX29', 'ELIX3', 'ELIX4', 'ELIX5', 'ELIX6', 'ELIX7',
       'ELIX8', 'ELIX9', 'countClaims', 'highUtilizer'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    8000 non-null   object
 1   ELIX1         8000 non-null   int64
 2   ELIX10        8000 non-null   int64
 3   ELIX11        8000 non-null   int64
 4   ELIX12        8000 non-null   int64
 5   ELIX13        8000 non-null   int64
 6   ELIX14        8000 non-null   int64
 7   ELIX15        8000 non-null   int64
 8   ELIX16        8000 non-null   int64
 9   ELIX17        8000 non-null   int64
 10  ELIX18        8000 non-null   int64
 11  ELIX19        8000 non-null   int64
 12  ELIX2         8000 non-null   int64
 13  ELIX20        8000 non-null   int64
 14  ELIX21        8000 non-null   int64
 15  ELIX22        8000 non-null   int64
 16  ELIX23        8000 non-null   int64
 17  ELIX24        8000 non-null   int64
 18  ELIX25        8000 non-null   int64
 19  ELIX26        8000 non-null   int64
 20  ELIX27        8000 non-null   int64
 21  ELIX28        8000 non-null   int64
 22  ELIX29        8000 non-null   int64
 23  ELIX3         8000 non-null   int64
 24  ELIX4         8000 non-null   int64
 25  ELIX5         8000 non-null   int64
 26  ELIX6         8000 non-null   int64
 27  ELIX7         8000 non-null   int64
 28  ELIX8         8000 non-null   int64
 29  ELIX9         8000 non-null   int64
 30  countClaims   8000 non-null   int64
 31  highUtilizer  8000 non-null   int64
dtypes: int64(31), object(1)
memory usage: 2.0+ MB

In [43]:
#summary statistics
df.describe()

,ELIX1,ELIX10,ELIX11,ELIX12,ELIX13,ELIX14,ELIX15,ELIX16,ELIX17,ELIX18,...,ELIX29,ELIX3,ELIX4,ELIX5,ELIX6,ELIX7,ELIX8,ELIX9,countClaims,highUtilizer
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,...,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000
mean,0.177375,0.006250,0.050000,0.175750,0.148375,0.260000,0.102000,0.093375,0.007875,0.204625,...,0.234750,0.069250,0.076500,0.076000,0.165125,0.05825,0.137250,0.408875,40.516750,0.077750
std,0.382010,0.078814,0.217959,0.380631,0.355494,0.438662,0.302667,0.290975,0.088397,0.403453,...,0.423869,0.253895,0.265813,0.265015,0.371317,0.23423,0.344133,0.491657,51.559706,0.267795
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,12.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,25.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,50.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,885.000000,1.000000

In [44]:
#missing vlaues - 0 sum means no nulls
df.isnull().sum().sort_values(ascending=False)

patient_id      0
ELIX1           0
countClaims     0
ELIX9           0
ELIX8           0
ELIX7           0
ELIX6           0
ELIX5           0
ELIX4           0
ELIX3           0
ELIX29          0
ELIX28          0
ELIX27          0
ELIX26          0
ELIX25          0
ELIX24          0
ELIX23          0
ELIX22          0
ELIX21          0
ELIX20          0
ELIX2           0
ELIX19          0
ELIX18          0
ELIX17          0
ELIX16          0
ELIX15          0
ELIX14          0
ELIX13          0
ELIX12          0
ELIX11          0
ELIX10          0
highUtilizer    0
dtype: int64

In [45]:
#identify strongest features/predictors
corr['highUtilizer'].abs().sort_values(ascending=False)

highUtilizer    1.000000
countClaims     0.756297
ELIX6           0.216613
ELIX14          0.205693
ELIX13          0.190034
ELIX8           0.178564
ELIX21          0.164391
ELIX27          0.143879
ELIX18          0.136217
ELIX9           0.128830
ELIX29          0.115627
ELIX16          0.100949
ELIX19          0.093812
ELIX1           0.087588
ELIX11          0.081176
ELIX3           0.069735
ELIX15          0.068723
ELIX24          0.067334
ELIX7           0.067303
ELIX22          0.064172
ELIX25          0.062028
ELIX20          0.061843
ELIX28          0.061786
ELIX12          0.059709
ELIX26          0.056485
ELIX5           0.055890
ELIX4           0.053420
ELIX17          0.042786
ELIX10          0.042129
ELIX2           0.033783
ELIX23          0.013788
Name: highUtilizer, dtype: float64

In [46]:
#profile for high utilizers
corr['highUtilizer'].abs().sort_values(ascending=False)

highUtilizer    1.000000
countClaims     0.756297
ELIX6           0.216613
ELIX14          0.205693
ELIX13          0.190034
ELIX8           0.178564
ELIX21          0.164391
ELIX27          0.143879
ELIX18          0.136217
ELIX9           0.128830
ELIX29          0.115627
ELIX16          0.100949
ELIX19          0.093812
ELIX1           0.087588
ELIX11          0.081176
ELIX3           0.069735
ELIX15          0.068723
ELIX24          0.067334
ELIX7           0.067303
ELIX22          0.064172
ELIX25          0.062028
ELIX20          0.061843
ELIX28          0.061786
ELIX12          0.059709
ELIX26          0.056485
ELIX5           0.055890
ELIX4           0.053420
ELIX17          0.042786
ELIX10          0.042129
ELIX2           0.033783
ELIX23          0.013788
Name: highUtilizer, dtype: float64

In [47]:
# prepare data for training and testing
# Create at least three classification models for predicting high utilization based on Year 1 data
# Here you use year 1 as input and Year 2 utilization as output

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# target
y = df['highUtilizer']

# features (drop target)
X = df.drop(columns=['highUtilizer'])
#drop patient-id
X = df.drop(columns=['patient_id'])

# handle categorical variables (if any)
X = pd.get_dummies(X, drop_first=True)

# train-test split -- 80% training and 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [50]:
# scale features -- good practice
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [51]:
# model A: logistic regression (baseline)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)
y_prob_log = log_model.predict_proba(X_test_scaled)[:, 1]

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("AUC:", roc_auc_score(y_test, y_prob_log))

Logistic Regression
Accuracy: 1.0
AUC: 1.0

In [52]:
# model B: Decision Tree 
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(max_depth=5, random_state=42)

tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_test)
y_prob_tree = tree_model.predict_proba(X_test)[:, 1]

print("\nDecision Tree")
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("AUC:", roc_auc_score(y_test, y_prob_tree))

Decision Tree
Accuracy: 1.0
AUC: 1.0

In [53]:
#model C: Random Forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("\nRandom Forest")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("AUC:", roc_auc_score(y_test, y_prob_rf))

Random Forest
Accuracy: 1.0
AUC: 1.0

In [54]:
# which model performs the best model predicting high utilization in year 2?

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_log),
        accuracy_score(y_test, y_pred_tree),
        accuracy_score(y_test, y_pred_rf)
    ],
    'AUC': [
        roc_auc_score(y_test, y_prob_log),
        roc_auc_score(y_test, y_prob_tree),
        roc_auc_score(y_test, y_prob_rf)
    ]
})

print(results)

                 Model  Accuracy  AUC
0  Logistic Regression       1.0  1.0
1        Decision Tree       1.0  1.0
2        Random Forest       1.0  1.0

In [56]:
# create regression model for predicting number of claims in Y2 based on Y1 data
# define target and features
# target
y = df['countClaims']  

# features
X = df.drop(columns=['countClaims', 'highUtilizer'], errors='ignore')

In [57]:
# test train split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [60]:
# linear regression (baseline - Model A)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

y_pred_lin = lin_model.predict(X_test)

print("Linear Regression")
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lin)))
print("R2:", r2_score(y_test, y_pred_lin))

ValueError: could not convert string to float: 'PAT150984'

In [61]:
# Lasso Regression (Model B)
from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train_scaled, y_train)

y_pred_lasso = lasso_model.predict(X_test_scaled)

print("\nLASSO Regression")
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lasso)))
print("R2:", r2_score(y_test, y_pred_lasso))

LASSO Regression
RMSE: 49.39993598092842
R2: -0.006706271775168693

In [62]:
# compare the performance of the regression models
results = pd.DataFrame({
    'Model': ['Linear', 'LASSO'],
    'RMSE': [
        np.sqrt(mean_squared_error(y_test, y_pred_lin)),
        np.sqrt(mean_squared_error(y_test, y_pred_lasso))
    ],
    'R2': [
        r2_score(y_test, y_pred_lin),
        r2_score(y_test, y_pred_lasso)
    ]
})
print(results)

    Model       RMSE        R2
0  Linear  43.642992  0.214260
1   LASSO  49.399936 -0.006706